// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tearoaeqtayjooszngvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlYXJvYWVxdGF5am9vc3puZ3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2OTA2NjgsImV4cCI6MjA4NzI2NjY2OH0.lQrAdUXJ6DFgVfBTGLFC5cqW0_GBL5xUtzeTLUIKB-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});